services:
  nextjs:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: alfred-app

    ports:
      - "8081:3000"
    env_file:
      - .env.local

    environment:
      NODE_ENV: production
      NEO4J_BOLT_URL: bolt://neo4j:7687

    depends_on:
      - neo4j

  neo4j:
    image: neo4j:2025.12.1
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: "neo4j/password"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: